name = "nexus-core"
main = "index.js"
compatibility_date = "2025-01-01"
account_id = "0f5d849a31acd27b71eb73fda2f20e4c"
workers_dev = true

[ai]
binding = "AI"

[triggers]
crons = ["0 3 * * *"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
